--Vista VentasxTransmision
CREATE OR REPLACE VIEW VENTAS_TRANSMISION AS
SELECT TIPO, COUNT(TIPO) AS CANTIDAD_VENTAS
FROM TRANSMISION
JOIN VEHICULO ON TRANSMISION.ID = VEHICULO.TRANSMISION_ID
JOIN DETALLE_VENTA ON VEHICULO.ID_V = DETALLE_VENTA.VEHICULO_ID_V
JOIN VENTA ON DETALLE_VENTA.VENTA_CLAVE = VENTA.CLAVE 
GROUP BY TIPO
WITH READ ONLY;

SELECT * FROM VENTAS_TRANSMISION;

--Vista VentasxConsecionaria
CREATE OR REPLACE VIEW VENTAS_CONSECIONARIA AS
SELECT NOMBRE, ESTADO, ALC_MUN, COLONIA,CP, COUNT(VENTA.CLAVE) AS CANTIDAD_VENTAS
FROM CONCESIONARIA
JOIN VENTA ON CONCESIONARIA.CLAVE = VENTA.CONCESIONARIA_CLAVE
JOIN DIRECCION ON DIRECCION.ID = CONCESIONARIA.DIRECCION_ID
JOIN ESTADO ON DIRECCION.ESTADO_ID = ESTADO.ID
JOIN ALC_MUN ON DIRECCION.ALC_MUN_ID = ALC_MUN.ID
GROUP BY NOMBRE, ESTADO, ALC_MUN, COLONIA,CP  
HAVING COUNT(VENTA.CLAVE) = (
    SELECT MAX(CANTIDAD_VENTAS)
    FROM(
        SELECT NOMBRE, ESTADO, ALC_MUN, COLONIA,CP, COUNT(VENTA.CLAVE) AS CANTIDAD_VENTAS
        FROM CONCESIONARIA
        JOIN VENTA ON CONCESIONARIA.CLAVE = VENTA.CONCESIONARIA_CLAVE
        JOIN DIRECCION ON DIRECCION.ID = CONCESIONARIA.DIRECCION_ID
        JOIN ESTADO ON DIRECCION.ESTADO_ID = ESTADO.ID
        JOIN ALC_MUN ON DIRECCION.ALC_MUN_ID = ALC_MUN.ID
        GROUP BY NOMBRE, ESTADO, ALC_MUN, COLONIA,CP
        ORDER BY NOMBRE ASC
        )
    )
WITH READ ONLY;

SELECT * FROM VENTAS_CONSECIONARIA;

--Vista VentaxEmpleado
CREATE OR REPLACE VIEW VENTAS_EMPLEADO AS
SELECT NOMBRE, COUNT(VENTA.CLAVE) AS CANTIDAD
FROM EMPLEADO
JOIN VENTA ON VENTA.EMPLEADO_ID_E = EMPLEADO.ID_E
GROUP BY NOMBRE
HAVING COUNT(VENTA.CLAVE) = (
    SELECT MAX(CANTIDAD)
    FROM(
        SELECT NOMBRE, COUNT(VENTA.CLAVE) AS CANTIDAD
        FROM EMPLEADO
        JOIN VENTA ON VENTA.EMPLEADO_ID_E = EMPLEADO.ID_E
        GROUP BY NOMBRE
        )
    )
WITH READ ONLY;
    
SELECT * FROM VENTAS_EMPLEADO;

--Vista DetallesVehiculo
CREATE OR REPLACE VIEW DETALLES_VEHICULO AS
SELECT VEHICULO.VIN,MARCA.MARCA,MODELO.MODELO,VEHICULO.ANIO, COLOR.COLOR, TIPO.TIPO, VEHICULO.LINEA, TRANSMISION.TIPO AS TRANSMISION, VEHICULO.PRECIO,
ESTADO_V.ESTADO, VEHICULO.FECHA_INGRESO,VEHICULO.NUM_MOTOR, TIPO_MOTOR.TIPO AS TIPO_MOTOR, VEHICULO.CAPACIDAD, VEHICULO.NUM_CILINDROS, VEHICULO.NUM_PUERTAS,
PROVEEDOR.EMPRESA AS PROVEEDOR,VENTA.FECHA_VENTA,VENTA.FECHA_ENTREGA, VENTA.NO_FACTURA, CLIENTE.NOMBRE AS NOMBRE_CLIENTE, EMPLEADO.NOMBRE AS NOMBRE_EMPLEADO, 
CONCESIONARIA.NOMBRE AS NOMBRE_CONCESIONARIA,
CONCESIONARIA.PAGINA_WEB, CONCESIONARIA.RFC,TIPO_GARANTIA.GARANTIA,METODO_PAGO.METODO
FROM VEHICULO
JOIN MARCA ON VEHICULO.MARCA_ID = MARCA.ID
JOIN MODELO ON VEHICULO.MODELO_ID = MODELO.ID
JOIN COLOR ON VEHICULO.COLOR_ID = COLOR.ID
JOIN TIPO ON VEHICULO.TIPO_ID = TIPO.ID
JOIN TRANSMISION ON VEHICULO.TRANSMISION_ID = TRANSMISION.ID
JOIN ESTADO_V ON VEHICULO.ESTADO_V_ID = ESTADO_V.ID
JOIN TIPO_MOTOR ON VEHICULO.TIPO_MOTOR_ID = TIPO_MOTOR.ID
JOIN PROVEEDOR ON VEHICULO.PROVEEDOR_ID_FK = PROVEEDOR.ID_P
JOIN DETALLE_VENTA ON VEHICULO.ID_V = DETALLE_VENTA.VEHICULO_ID_V
JOIN VENTA ON DETALLE_VENTA.VENTA_CLAVE = VENTA.CLAVE
JOIN CLIENTE ON VENTA.CLIENTE_ID_C = CLIENTE.ID_C
JOIN EMPLEADO ON VENTA.EMPLEADO_ID_E = EMPLEADO.ID_E
JOIN CONCESIONARIA ON VENTA.CONCESIONARIA_CLAVE = CONCESIONARIA.CLAVE
JOIN TIPO_GARANTIA ON VENTA.TIPO_GARANTIA_ID = TIPO_GARANTIA.ID
JOIN DETALLE_PAGO ON VENTA.CLAVE = DETALLE_PAGO.VENTA_CLAVE
JOIN METODO_PAGO ON DETALLE_PAGO.METODO_PAGO_ID = METODO_PAGO.ID
WHERE VEHICULO.VIN = '1HGBH41JXMN109186'
WITH READ ONLY;

SELECT * FROM DETALLES_VEHICULO;

--Vista GananciasxMes
CREATE OR REPLACE VIEW GANANCIASMES AS
SELECT EXTRACT(MONTH FROM FECHA_VENTA) AS MONTH, SUM(MONTO_METODO) AS GANANCIAS_T
FROM DETALLE_PAGO
JOIN VENTA ON VENTA.CLAVE = DETALLE_PAGO.VENTA_CLAVE
WHERE EXTRACT(MONTH FROM FECHA_VENTA) = 11
GROUP BY EXTRACT(MONTH FROM FECHA_VENTA)
ORDER BY EXTRACT(MONTH FROM FECHA_VENTA) ASC
WITH READ ONLY;

SELECT * FROM GANANCIASMES;

--Vista VentasXMetodo
CREATE OR REPLACE VIEW VENTAS_METODO AS
SELECT METODO, COUNT (METODO_PAGO_ID) AS TOTAL
FROM METODO_PAGO
JOIN DETALLE_PAGO ON METODO_PAGO.ID = DETALLE_PAGO.METODO_PAGO_ID
GROUP BY METODO
HAVING COUNT (METODO_PAGO_ID) = (
    SELECT MAX(TOTAL)
    FROM(
        SELECT METODO, COUNT (METODO_PAGO_ID) AS TOTAL
        FROM METODO_PAGO
        JOIN DETALLE_PAGO ON METODO_PAGO.ID = DETALLE_PAGO.METODO_PAGO_ID
        GROUP BY METODO
        )
)
WITH READ ONLY;

SELECT * FROM VENTAS_METODO;



